### ISSUE TITLE
05_zfs_linux.py fails with SyntaxError

### ISSUE THREAD

**Issue by Greek64** [johnramsden/zedenv-grub#10]
When trying to activate a BE via zedenv with this grub plugin installed, the ```grub-kmconfig``` command fails with
```
File "05_zfs_linux.py", line 20
    env_command = ['sh', '-c', f'set -a && . {file} && env']
                                                          ^
SyntaxError: invalid syntax
```

The reason is that the wrong python version is invoked.
Because I'm on Debian I had to install Python3.6 from source, but did so using the ```make altinstall``` command, meaning that the system default python is still version 3.5.x

A modification of the Shebang of this file to python3.6 would fix this error.

**Comment by johnramsden** [comment]
Unfortunately changing the shebang would break the plugin for anyone on 3.7. Since python 3.6 or greater is required, in this case it's probably best to have the user modify their shebang manually.

**Comment by Greek64** [comment]
Ohh. I thought python3.6 was a requirement. 
Didn't think of higher versions.

Yeah, I'll keep it local.
