### ISSUE TITLE
initrd is not being added to grub.cfg on gentoo with a genkernel configuration

### ISSUE THREAD

**Issue by a-schaefers** [johnramsden/zedenv-grub#15]
After update-grub in gentoo with a genkernel configuration, the resulting grub.cfg contains no initrd in the gentoo stanza.

The line I need zedenv to add is formatted by the grub-mkconfig scripts as:

initrd	/root/gentoo@/boot/initramfs-genkernel-x86_64-4.18.19-gentoo

but the initrd section of grub.cfg generated by 00_header and 05_zfs_linux.py is empty. There is no initrd in the stanza at all.

This results in kernel panic on next boot.

I took a look at /etc/grub.d/05_zfs_linux.py and n[oticed lines around 416](https://github.com/johnramsden/zedenv-grub/blob/master/grub.d/05_zfs_linux.py#L416)  It appears you have already accounted for the genkernel formatting in the codebase, so I think this may be a bug?

**Comment by a-schaefers** [comment]
The following is a generic _[working]_ grub.cfg entry for this gentoo install:

```
menuentry 'Gentoo GNU/Linux' --class gentoo --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-199c8f7c6a7869f1' {
	load_video
	if [ "x$grub_platform" = xefi ]; then
		set gfxpayload=keep
	fi
	insmod gzio
	insmod part_gpt
	insmod part_gpt
	insmod zfs
	set root='hd1,gpt1'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd1,gpt1 --hint-efi=hd1,gpt1 --hint-baremetal=ahci1,gpt1  --hint-bios=hd0,gpt1 --hint-efi=hd0,gpt1 --hint-baremetal=ahci0,gpt1  199c8f7c6a7869f1
	else
	  search --no-floppy --fs-uuid --set=root 199c8f7c6a7869f1
	fi
	echo	'Loading Linux x86_64-4.18.19-gentoo ...'
	linux	/root/gentoo@/boot/kernel-genkernel-x86_64-4.18.19-gentoo root=ZFS=rpool/root/gentoo ro verbose i915.enable_fbc=1 init=/lib/systemd/systemd dozfs=cache root=ZFS=rpool/root/gentoo 
	echo	'Loading initial ramdisk ...'
	initrd	/root/gentoo@/boot/initramfs-genkernel-x86_64-4.18.19-gentoo
}
```

And now the stanza that zedenv generated:

```
submenu 'Boot Environments (Debian GNU/Linux)' $menuentry_id_option 'gnulinux-advanced-be-rpool/root/stable' {
	menuentry 'Debian GNU/Linux BE [gentoo] with Linux genkernel-x86_64-4.18.19-gentoo' --class debian --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-genkernel-x86_64-4.18.19-gentoo-advanced-rpool/root/gentoo' {
		load_video
		insmod gzio
		insmod zfs
		set root='hd1,gpt1'
		if [ x$feature_platform_search_hint = xy ]; then
		  search --no-floppy --fs-uuid --set=root 199c8f7c6a7869f1 --hint-bios=hd1,gpt1 --hint-efi=hd1,gpt1 --hint-baremetal=ahci1,gpt1  --hint-bios=hd0,gpt1 --hint-efi=hd0,gpt1 --hint-baremetal=ahci0,gpt1 
		else
		  search --no-floppy --fs-uuid --set=root 199c8f7c6a7869f1
		fi
		echo 'Loading Linux genkernel-x86_64-4.18.19-gentoo ...'
		linux /root/gentoo@/boot/kernel-genkernel-x86_64-4.18.19-gentoo root=ZFS=rpool/root/gentoo rw  dozfs=cache verbose i915.enable_fbc=1 apparmor=0 init=/lib/systemd/systemd
	}
}
```

**Comment by a-schaefers** [comment]
Okay, there is a missing comma on line 416

after adding  
`f"initramfs-genkernel-x86_64-4.18.19-gentoo"] `
to the list being iterated it includes the initrd on the stanza. Now I am trying to fix the python for it.

**Comment by a-schaefers** [comment]
I have this fixed.

**Comment by a-schaefers** [comment]
PR coming shortly

**Comment by a-schaefers** [comment]
print(self.version, file=sys.stderr) revealed to me that the value was genkernel-x86_64-4.18.19-gentoo

so we need to add f"initramfs-{self.version}",

**Comment by johnramsden** [comment]
@a-schaefers so it doesn't have an `.img` extension?

**Comment by a-schaefers** [comment]
correct
