### ISSUE TITLE
zedenv create and zedenv rename does not update-grub

### ISSUE THREAD

**Issue by a-schaefers** [johnramsden/zedenv-grub#21]
zedenv create and zedenv rename do not update-grub, while zedenv activate and zedenv destroy do.

I am not sure if this behavior is intended or not. (Is this a bug?) I am far from being an expert on "what should be" and "what shouldn't be" in these matters.

I do personally prefer zedenv create and rename will stay in sync with my bootloader. I currently am using a helper bash wrapper function in root's ~/.bashrc as a workaround:

```
zedenv() {
    if [[ $1 == "create" ]] || [[ $1 == "rename" ]]
    then
        /usr/bin/zedenv "$@" && grub-mkconfig -o /boot/grub/grub.cfg
    else
        /usr/bin/zedenv "$@"
    fi
}
```

Thanks

**Comment by johnramsden** [comment]
This _was_ intended, since I kind of I was thinking about it more in terms of switching to a new boot environment, where you would want grub to be updated. I was following the FreeBSD beadm convention of only regenerating on activate. I guess I can see how you _would_ want the new boot environment to show up in the menu even when it hasn't been updated though. That probably makes more sense.

I don't see a lot of negatives to making it update grub, other than the fact that it will be slower. I'll add this in the next release.

**Comment by a-schaefers** [comment]
Interesting, cool! :)

I wonder also about "rename", I think it would be essential that rename would reflect on the menu, for example:

`beadm rename backup-foo-oldname backup-foo-newname`

and then in emergency if i needed to access "backup-foo-newname" i would be in some trouble if I didn't remember or the name and/or know how to use 'e' and grub edit the menuentry.

And if I'm not mistaken, all changes like this on FreeBSD reflect immediately on the boot loader (due to the nature of their different bootloader, I think?)-- while grub with zedenv does not.

For that matter also I think some people use create as a quick way to create a safe rollback:

```
beadm create safe-rollback

rm -rf /

# now hold down power button
```

Now choose safe-rollback from the bootloader.

**Comment by johnramsden** [comment]
Yes, now everything reflects immediately since the bootloader is aware of boot environments. I was talking more in terms of grub though and thought it only updated on activate, after checking just now it seems it _does_ update on rename, create and destroy. Which probably makes the most sense.

**Comment by a-schaefers** [comment]
Gotchya. Thanks again for all you're doing. :)

**Comment by johnramsden** [comment]
@a-schaefers I added the hooks into zedenv so that the plug-in can run a 'post' command. Did you feel like testing the changes from zedenv master, and the [zedenv-grub/issue#21](https://github.com/johnramsden/zedenv-grub/tree/issue/%2321) branch before I close this?

**Comment by a-schaefers** [comment]
Sure yeah. I will test it right now.

**Comment by a-schaefers** [comment]
The zedenv-grub/issue#21 branch works great for me
