### ISSUE TITLE
CentOS 7 root on ZFS with grub2

### ISSUE THREAD

**Issue by thornmir** [johnramsden/zedenv-grub#23]
Hi, 
I discovered zedenv through your blog recently. 
I wish to use it to manage my ZFS mirror pool on a personal server. 
I used this [wiki](https://github.com/zfsonlinux/pkg-zfs/wiki/HOWTO-install-EL7-(CentOS-RHEL)-to-a-Native-ZFS-Root-Filesystem)  to setup my root on ZFS.

Here is my Dataset partitioning : (nothing is mounted as legacy)

```
NAME                      USED  AVAIL  REFER  MOUNTPOINT
zroot                    9.88G  1.72T   144K  /zroot
zroot/dom0               9.88G  1.72T   136K  /zroot/dom0
zroot/dom0/ROOT          1.38G  1.72T   136K  none
zroot/dom0/ROOT/default  2.88M  1.72T  1.37G  /
zroot/dom0/ROOT/first    1.37G  1.72T  1.37G  /
zroot/dom0/boot           276K  1.72T   136K  /zroot/dom0/boot
zroot/dom0/boot/grub      140K  1.72T   140K  /boot/grub
zroot/dom0/home           164K  1.72T   164K  /home
zroot/dom0/swap          8.50G  1.72T    68K  -
zroot/dom0/tmp            332K  1.72T   332K  /tmp
zroot/dom0/usr            136K  1.72T   136K  /usr
zroot/dom0/var            408K  1.72T   136K  /var
zroot/dom0/var/lib        136K  1.72T   136K  /var/lib
zroot/dom0/var/log        136K  1.72T   136K  /var/log
zroot/domU                136K  1.72T   136K  none
```

/first /boot and /boot/grub were added following the documentation.
First I had an issue about the bootfs propertie on the zroot pool. This property is not needed in my setup and so I ran `zpool set bootfs=zroot/dom0/ROOT/default zroot` and it fixed the problem. 
Secondly it seems that i'm not using grub the same way you are because my grub.cfg is located at /boot/grub2/grub.cfg. This folder is located on the ZFS root Dataset and it working like a charm. 
Moreover grub-mkconfig does not exist on my system only grub2-mkconfig (could be fixed with just a ln-s but I fear it would break something)

So i'm not a specialist my main issue is that creating and activating a BE does not create a file at /boot/grub2 and so nothing happen on reboot. 

Here is the menuentry of mygrub.cfg that boot my system : (GPT with BIOS not efi)
```
menuentry 'CentOS Linux (3.10.0-957.1.3.el7.x86_64) 7 (Core)' --class centos --class gnu-linux --class gnu --class os --unrestricted $menuentry_id_option 'gnulinux-3.10.0-957.1.3.el7.x86_64-advanced-a61d884a39fd8806' {
        load_video
        set gfxpayload=keep
        insmod gzio
        insmod part_gpt
        insmod part_gpt
        insmod zfs
        set root='hd0,gpt2'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint-bios=hd0,gpt2 --hint-efi=hd0,gpt2 --hint-baremetal=ahci0,gpt2  --hint-bios=hd1,gpt2 --hint-efi=hd1,gpt2 --hint-baremetal=ahci1,gpt2  a61d884a39fd8806
        else
          search --no-floppy --fs-uuid --set=root a61d884a39fd8806
        fi
        linux16 /dom0/ROOT/default@/boot/vmlinuz-3.10.0-957.1.3.el7.x86_64 root=ZFS=zroot/dom0/ROOT/default ro rhgb quiet 
        initrd16 /dom0/ROOT/default@/boot/initramfs-3.10.0-957.1.3.el7.x86_64.img
}

```

**Comment by johnramsden** [comment]
Added a `grubsubdir` property:

```
"property": "grubsubdir",
"description": "Set name of subdirectory under boot.",
"default": "grub"
```

You can set it to `grub2` with `zedenv set org.zedenv.grub:grubsubdir=grub2`.

Regarding the location of the files. I would go with the symlink, it shouldn't cause any problems unless there's a file already there.

Let me know if that works for you.

**Comment by thornmir** [comment]
OK 
I have run
``` 
zedenv set org.zedenv.grub:grubsdir=grub
ln -s /usr/sbin/grub2-mkconfig /usr/sbin/grub-mkconfig
ln -s /usr/sbin/grub2-install  /usr/sbin/grub-install
ln -s /usr/sbin/grub2-probe /usr/sbin/grub-probe
```
And grub.cfg.new appears on /boot/grub2/ 
Thanks

EDIT : Just in case it seem reasonable to do it on all grub2-* commands 
```
for grub in $(find /usr/sbin/grub2* -printf "%f "); do  ln -s /usr/sbin/$grub /usr/sbin/$(echo $grub |sed -e s/grub2/grub/g); done
```

**Comment by johnramsden** [comment]
Sorry that actually should have been `zedenv set org.zedenv.grub:grubsubdir=grub2`. The subdirectory will be whatever you set it to.
