### ISSUE TITLE
Menuentry ordering does not support Debian-Style Kernel Versioning

### ISSUE THREAD

**Issue by Greek64** [johnramsden/zedenv-grub#31]
The ordering of `05_zfs_linux.py` does not handle Debian Kernel versioning correctly.

E.g.
```
vmlinuz-4.20.0-10-amd64
vmlinuz-4.20.0-11-amd64
vmlinuz-4.20.0-1-amd64
vmlinuz-4.20.0-5-amd64
vmlinuz-4.20.0-6-amd64
vmlinuz-4.20.0-8-amd64
```

Is ordered as follows:
```
4.20.0-1-amd64
4.20.0-11-amd64
4.20.0-10-amd64
4.20.0-8-amd64
4.20.0-5-amd64
4.20.0-6-amd64
```

**Comment by johnramsden** [comment]
@mkessler001's patch in #32 should have fixed this. Are you able to test the change to confirm @Greek64?

You should be able to just change your local version of `/etc/grub.d/05_zfs_linux.py` to be the same as master. The only change is on L745:

https://github.com/johnramsden/zedenv-grub/blob/ff6a13c348bb27e9f4f9f057049faed74be5169d/grub.d/05_zfs_linux.py#L745

**Comment by Greek64** [comment]
Can confirm it working.
Thanks!
