### ISSUE TITLE
Incorrect dependencies in PKGBUILD-git

### ISSUE THREAD

**Issue by danboid** [johnramsden/zedenv-grub#5]
I have checked out the grub-generators branch but the PKGBUILD-git fails because it is looking for python-pyzfscmds and zedenv depencies instead of python-pyzfscmds-git and zedenv-git, which is what you get if you install those from their respective PKGBUILD-git files.

**Comment by johnramsden** [comment]
I've been using the non-git versions with it. If i change the `PKGBUILD-git` entries to `provides=('zedenv')`, it should work with `zedenv-git` next time, for now maybe use the non git dependencies..

**Comment by danboid** [comment]
I presumed that as you wanted me to test a git branch of the grub plugin that I should be using the git versions of pyzfscmds and zedenv, seeing as you didn't specify the versions I should test.

**Comment by johnramsden** [comment]
I don't actually have a `pyzfscmds` git version in the AUR, and the git version is pretty much where the release version is that so you should be fine using that one.

It's really more about testing the plugin, and I think testing with the release version of `zedenv` is probably best anyway for now.

**Comment by danboid** [comment]
OK, I'll try again with the release version of zedenv but I'll have to manually copy the generator into /etc/grub.d else the grub plugin won't work, will it?

**Comment by johnramsden** [comment]
No, the `setup.py` _should_ be installing it for you.

https://github.com/johnramsden/zedenv-grub/blob/3fb25d55f493539fa433b63b12434e50d7315556/setup.py#L52

**Comment by danboid** [comment]
The generator does get installed when using the PKGBUILD-git in the current grub-generators branch so closing.
