### ISSUE TITLE
PKGBUILD/setup.py doesn't install GRUB generator

### ISSUE THREAD

**Issue by danboid** [johnramsden/zedenv-grub#6]
If you install the grub-generators branch of zedenv-grub via setup.py it copies the GRUB generator to /etc/grub.d/05_zfs_linux.py but the PKGBUILD-git file doesn't copy any generator file into /etc/grub.d

**Comment by danboid** [comment]
Having looked at the PKGBUILD I can see that it runs setup.py so I expect error is actually within the setup.py instead of the PKGBUILD.

**Comment by johnramsden** [comment]
I changed it to 05 so the zedenv entries default to before the 10_linux ones. Is it being installed for you?

**Comment by danboid** [comment]
No, I don't have any zfs scripts in /etc/grub.d after installing the zedenv-grub-git package.

**Comment by johnramsden** [comment]
Strange, I'll check it out.

**Comment by johnramsden** [comment]
So this is what I did on a brand new VM to install:

```
ls /etc/grub.d
00_header  10_linux  20_linux_xen  30_os-prober  40_custom  41_custom  README
```

With an AUR manager:

```
yay -S zedenv
```

```
git clone https://github.com/johnramsden/zedenv-grub.git
cd zedenv-grub
git checkout grub-generators
```

Change Source in `packaging/arch/PKGBUILD-git`

```
cd packaging/arch/
nano PKGBUILD-git
cat PKGBUILD-git

source=('zedenv-grub::git+https://github.com/johnramsden/zedenv-grub#branch=grub-generators')
```

Build and install package:

```
makepkg -sic -p PKGBUILD-git
```

```
ls /etc/grub.d                                          
00_header  05_zfs_linux.py  10_linux  20_linux_xen  30_os-prober  40_custom  41_custom  README
```

---

@danboid Maybe you were using the master branch? Perhaps I should have mentioned that you needed to use the 'grub-generators' branch. Let me know if that works.

**Comment by danboid** [comment]
I was using the grub-generators branch (I posted my installation steps in another bug report) but I didn't edit the PKGBUILD-git to point to the correct branch (after switching branch) as I expected that would've been set correctly. Not so!

**Comment by danboid** [comment]
Please sync the AUR PKGBUILDs for zedenv with the ones on github. The PKGBUILDs included with the source (on github) should be the canonical versions instead of those on the AUR, which I instinctively trust less. Also fix the PKBUILD-git in the grub-gen branch of the plugin so it doesn't need to edited please.

**Comment by danboid** [comment]
The current grub-generators branch PKGBUILD-git does install the generator so closing.
